<?php

use yii\db\Migration;

class m251021_232801_create_orders extends Migration
{
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $this->createTable('ORDERS', [
            'ID' => 'NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY',
            'CLIENT_ID' => $this->integer()->notNull(),
            'TOTAL_VALUE' => $this->decimal(10, 2)->notNull()->defaultValue(0),
            'STATUS' => $this->string(10)->notNull()->defaultValue('PENDENTE'),
            'ORDER_DATE' => $this->timestamp()->notNull()->defaultExpression('SYSTIMESTAMP'),
        ]);

        $this->execute(
            'ALTER TABLE ORDERS
             ADD CONSTRAINT FK_ORDERS_CLIENTS
             FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS(ID)
             ON DELETE CASCADE'
        );

        $this->execute(
            "ALTER TABLE ORDERS
             ADD CONSTRAINT CK_ORDERS_STATUS
             CHECK (status IN ('PENDENTE','PAGO','CANCELADO'))"
        );
    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        $this->execute("ALTER TABLE ORDERS DROP CONSTRAINT FK_ORDERS_CLIENTS");
        $this->execute("ALTER TABLE ORDERS DROP CONSTRAINT CK_ORDERS_STATUS");
        $this->dropTable('ORDERS');
    }

}
