<?php

use yii\db\Migration;

class m251021_232751_create_clients extends Migration
{
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $this->createTable('CLIENTS', [
            'ID' => 'NUMBER(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY',
            'NAME' => $this->string(100)->notNull(),
            'EMAIL' => $this->string(100)->notNull(),
            'STATUS' => $this->string(10)->notNull()->defaultValue('ATIVO'),
            'CREATED_AT' => $this->timestamp()->notNull()->defaultExpression('SYSTIMESTAMP'),
        ]);

        $this->execute(
            "ALTER TABLE CLIENTS
             ADD CONSTRAINT CK_CLIENTS_STATUS
             CHECK (status IN ('ATIVO','INATIVO'))"
        );

        $this->execute('ALTER TABLE CLIENTS ADD CONSTRAINT UQ_CLIENTS_EMAIL UNIQUE (EMAIL)');
    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        $this->execute('ALTER TABLE CLIENTS DROP CONSTRAINT UQ_CLIENTS_EMAIL');
        $this->dropTable('CLIENTS');
    }
}
